spring:
  application:
    name: aggregator
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server
      fail-fast: true
      retry:
        useRandomPolicy: true
        max-interval: 6000
  config:
    import: "optional:configserver:"

  eureka:
    client:
      serviceUrl:
        defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/