spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:1488/analyzer-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

jpa:
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect

grpc:
  client:
    hub-router:
      address: 'static://localhost:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

app:
  kafka:
    consumer:
      hub:
        bootstrap-server: localhost:9092
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: serialization.HubEventDeserializer
        group-id: events.analyzer
        enable-auto-commit: false
        time-out: 1000
      snapshot:
        bootstrap-server: localhost:9092
        group-id: snapshot.analyzer
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: serialization.SensorsSnapshotDeserializer
        enable-auto-commit: false
        time-out: 500
    topics:
      hub-events: telemetry.hubs.v1
      snapshots-events: telemetry.snapshots.v1

logging:
  level:
    root: INFO
    org.springframework.kafka: DEBUG
    ru.yandex.practicum.analyzer: DEBUG
    net.devh.boot.grpc.client: DEBUG
